import { MigrationInterface, QueryRunner } from 'typeorm';

export class InsertProduto1720889741241 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
            insert into produto (descricao, custo, imagem) values ('QUEIJO MUSSARELA EM PEDACOS BIGBOM', 27.2970, null);
            insert into produto (descricao, custo, imagem) values ('QUEIJO MUSSARELA RALADO BIGBOM', 27.2970, null);
            insert into produto (descricao, custo, imagem) values ('CALABRESA KG SADIA  PCT 5KG (CX20KG)', 10.2900, null);
            insert into produto (descricao, custo, imagem) values ('QUEIJO MUSSARELA BARRA VITALLY', 22.2000, null);
            insert into produto (descricao, custo, imagem) values ('QUEIJO MUSSARELA BARRA MATUPI (KG)', 31.0000, null);
            insert into produto (descricao, custo, imagem) values ('QUEIJO MUSSARELA BARRA DULEIT', 22.6500, null);
            insert into produto (descricao, custo, imagem) values ('CALABRESA KG SEARA PT 2,5KG (CX15KG)', 19.7796, null);
            insert into produto (descricao, custo, imagem) values ('SALSICHA KG', 5.0320, null);
            insert into produto (descricao, custo, imagem) values ('QUEIJO PRATO FATIADO BIGBOM 5KG', 21.0000, null);
            insert into produto (descricao, custo, imagem) values ('CHESTER LANCHE BARRA PERDIGAO KG', 10.6735, null);
            insert into produto (descricao, custo, imagem) values ('COXA C  SOBRECOXA INDIVIDUAL PIONEIRO (20KG)', 4.2513, null);
            insert into produto (descricao, custo, imagem) values ('FILE DE PEITO INDIVIDUAL SACHE PIONEIRO (20)', 6.1063, null);
            insert into produto (descricao, custo, imagem) values ('PEITO C OSSO INDIVIDUAL SACHE PIONEIRO (18)', 6.1729, null);
            insert into produto (descricao, custo, imagem) values ('BACON DEFUMADO CX 11KG OCIDENTAL', 10.4155, null);
            insert into produto (descricao, custo, imagem) values ('COSTELA RECOR SALGADA AURORA CX 10KG OCIDENTAL', 6.7814, null);
            insert into produto (descricao, custo, imagem) values ('RABO SUINO SALG AURORA CX 10KG OCIDENTAL', 6.9372, null);
            insert into produto (descricao, custo, imagem) values ('ORELHA SUINA SALG AURORA CX 10KG OCIDENTAL', 6.8962, null);
            insert into produto (descricao, custo, imagem) values ('PERNIL SUINO C O S P SALG AURORA CX 20KG OCIDENTAL', 6.9290, null);
            insert into produto (descricao, custo, imagem) values ('LING CALABRESA AURORA 13X400G CX 5,2KG OCIDENTAL', 18.5673, null);
            insert into produto (descricao, custo, imagem) values ('LING PAIO AURORA PCT 2,5KG CX 10KG OCIDENTAL', 17.9900, null);
            insert into produto (descricao, custo, imagem) values ('LING PORTUGUESA AURORA PCT 2,5KG CX 10KG OCIDENTAL', 12.8000, null);
            insert into produto (descricao, custo, imagem) values ('LING CALABRESA NOBRE PCT 2KG CX 10KG AURORA OCIDENTAL', 8.0900, null);
            insert into produto (descricao, custo, imagem) values ('INGREDIENTES PARA FEIJOADA CX 2X10KG OCIDENTAL', 7.7055, null);
            insert into produto (descricao, custo, imagem) values ('FRANGO CONG AVENORTE KG (20KG)', 4.9000, null);
            insert into produto (descricao, custo, imagem) values ('COSTELA SUINA SADIA (10)', 10.6995, null);
            insert into produto (descricao, custo, imagem) values ('PRESUNTO DE PERU EM PEDACOS BIGBOM KG', 15.5080, null);
            insert into produto (descricao, custo, imagem) values ('PRESUNTO DE PERU 500G BIGBOM', 10.8747, null);
            insert into produto (descricao, custo, imagem) values ('PRESUNTO DE PERU 200G BIGBOM', 10.8747, null);
            insert into produto (descricao, custo, imagem) values ('PRESUNTO COZIDO 200G BIGBOM', 10.0052, null);
            insert into produto (descricao, custo, imagem) values ('PRESUNTO COZIDO REZENDE SEARA BARRA KG', 5.4450, null);
            insert into produto (descricao, custo, imagem) values ('MORTADELA BARRA COMUM SADIA', 2.6280, null);
            insert into produto (descricao, custo, imagem) values ('MORTADELA COMUM 500G BIGBOM', 4.2908, null);
            insert into produto (descricao, custo, imagem) values ('MORTADELA BARRA BOLOGNELA BOLOGNA', 2.4150, null);
            insert into produto (descricao, custo, imagem) values ('MORTADELA BOLOGNA 200G  BIGBOM', 5.4626, null);
            insert into produto (descricao, custo, imagem) values ('MORTADELA BOLOGNA 500G  BIGBOM', 5.4626, null);
            insert into produto (descricao, custo, imagem) values ('CALABRESA RETA INTEIRA SADIA 2,5KG (03)', 9.6700, null);
            insert into produto (descricao, custo, imagem) values ('CALABRESA RETA 500G FATIADA BIGBOM', 8.1305, null);
            insert into produto (descricao, custo, imagem) values ('BACON MANTA', 13.9400, null);
            insert into produto (descricao, custo, imagem) values ('AFIAMBRADO EM PEDACOS BIGBOM', 5.2082, null);
            insert into produto (descricao, custo, imagem) values ('AFIAMBRADO 200G BIGBOM', 3.3000, null);
            insert into produto (descricao, custo, imagem) values ('QUEIJO MUSSARELA BARRA LUISA', 20.0000, null);
            insert into produto (descricao, custo, imagem) values ('QUEIJO MUSSARELA BARRA TOYA', 29.4000, null);
            insert into produto (descricao, custo, imagem) values ('QUEIJO PRATO EM PEDACOS BIGBOM', 35.6340, null);
            insert into produto (descricao, custo, imagem) values ('QUEIJO MUSSARELA BARRA PIRACANJUBA', 18.3000, null);
            insert into produto (descricao, custo, imagem) values ('QUEIJO PRATO FATIAMENTO BARRA GRANDE MATUPI', 0.0000, null);
            insert into produto (descricao, custo, imagem) values ('QUEIJO PRATO BARRA PIRACANJUBA', 0.0000, null);
            insert into produto (descricao, custo, imagem) values ('QUEIJO MUSSARELA BARRA MAIS', 18.3000, null);
            insert into produto (descricao, custo, imagem) values ('QUEIJO MUSSARELA BARRA J R (KG)', 20.5931, null);
            insert into produto (descricao, custo, imagem) values ('QUEIJO PRATO BARRA ALIANCA KG', 25.0500, null);
            insert into produto (descricao, custo, imagem) values ('PERU BARRA REZENDE KG SEARA KG', 13.8394, null);
            insert into produto (descricao, custo, imagem) values ('FRANGO CONG FLABOYAN KG (20KG)', 4.8000, null);
            insert into produto (descricao, custo, imagem) values ('COXA C  SOBRECOXA INDIVIDUAL A GOSTO(18)', 4.5000, null);
            insert into produto (descricao, custo, imagem) values ('COXA C  SOBRECOXA INDIVIDUAL CANCAO', 4.8795, null);
            insert into produto (descricao, custo, imagem) values ('QUEIJO MUSSARELA BARRA LIDERNORTE (KG)', 29.0000, null);
            insert into produto (descricao, custo, imagem) values ('QUEIJO PRATO RALADO BIGBOM', 26.6620, null);
            insert into produto (descricao, custo, imagem) values ('DESATIVADO SEM HISTORICO DE MOVIMENTACAO', 16.8976, null);
            insert into produto (descricao, custo, imagem) values ('DESATIVADO', 8.9500, null);
            insert into produto (descricao, custo, imagem) values ('FILE DE PEITO INDIVIDUAL SACHE MISTER (18)', 9.7000, null);
            insert into produto (descricao, custo, imagem) values ('PEITO C OSSO INDIVIDUAL SACHE AVENORTE (20)', 6.3000, null);
            insert into produto (descricao, custo, imagem) values ('PRESUNTO DE PERU BARRA KG SADIA', 12.2512, null);
        `);

    await queryRunner.query(`
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (1, 1, 16.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (2, 1, 17.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (3, 1, 14.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (4, 1, 18.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (5, 1, 19.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (6, 1, 18.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (7, 1, 24.4900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (8, 1, 5.3000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (9, 1, 24.4900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (10, 1, 13.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (11, 1, 5.3500);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (12, 1, 7.6000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (13, 1, 7.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (14, 1, 12.7000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (15, 1, 8.2700);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (16, 1, 8.4600);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (17, 1, 8.4100);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (18, 1, 8.4500);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (19, 1, 18.5700);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (20, 1, 17.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (21, 1, 12.8000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (22, 1, 8.0900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (23, 1, 9.4000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (24, 1, 5.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (25, 1, 13.6000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (26, 1, 14.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (27, 1, 15.9500);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (28, 1, 16.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (29, 1, 12.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (30, 1, 11.9000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (31, 1, 6.3000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (32, 1, 6.3000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (33, 1, 6.4400);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (34, 1, 9.9000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (35, 1, 9.9000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (36, 1, 11.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (37, 1, 13.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (38, 1, 21.0000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (39, 1, 4.0000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (40, 1, 6.9000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (41, 1, 18.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (42, 1, 20.7500);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (43, 1, 19.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (44, 1, 18.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (45, 1, 22.0000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (46, 1, 26.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (47, 1, 18.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (48, 1, 18.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (49, 1, 32.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (50, 1, 16.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (51, 1, 4.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (52, 1, 5.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (53, 1, 6.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (54, 1, 27.4900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (55, 1, 15.0000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (56, 1, 21.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (57, 1, 8.9500);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (58, 1, 11.6000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (59, 1, 8.7000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (60, 1, 14.5000);
    `);

    await queryRunner.query(`
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (1, 2, 16.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (2, 2, 17.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (3, 2, 14.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (4, 2, 18.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (5, 2, 19.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (6, 2, 18.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (7, 2, 24.4900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (8, 2, 5.3000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (9, 2, 24.4900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (10, 2, 13.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (11, 2, 5.3500);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (12, 2, 7.6000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (13, 2, 7.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (14, 2, 12.7000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (15, 2, 8.2700);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (16, 2, 8.4600);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (17, 2, 8.4100);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (18, 2, 8.4500);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (19, 2, 18.5700);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (20, 2, 17.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (21, 2, 12.8000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (22, 2, 8.0900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (23, 2, 9.4000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (24, 2, 5.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (25, 2, 13.6000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (26, 2, 14.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (27, 2, 15.9500);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (28, 2, 16.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (29, 2, 12.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (30, 2, 11.9000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (31, 2, 6.3000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (32, 2, 6.3000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (33, 2, 6.4400);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (34, 2, 9.9000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (35, 2, 9.9000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (36, 2, 11.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (37, 2, 13.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (38, 2, 21.0000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (39, 2, 4.0000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (40, 2, 6.9000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (41, 2, 18.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (42, 2, 20.7500);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (43, 2, 19.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (44, 2, 18.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (45, 2, 22.0000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (46, 2, 26.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (47, 2, 18.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (48, 2, 18.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (49, 2, 32.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (50, 2, 16.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (51, 2, 4.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (52, 2, 5.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (53, 2, 6.9900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (54, 2, 27.4900);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (55, 2, 15.0000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (56, 2, 21.5000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (57, 2, 8.9500);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (58, 2, 11.6000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (59, 2, 8.7000);
        insert into produtoloja ("idProduto", "idLoja", "precoVenda") values (60, 2, 14.5000);
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    queryRunner.query(`
        delete from produtoloja;
        `);

    queryRunner.query(`
        delete from produto;
        `);
  }
}
